test-job:
  tags:
    - bb5_map
  variables:
    bb5_account: proj83
  stage: test
  before_script:
    - module load unstable python py-bluepy py-virtualenv
    - CI_VENV="$(pwd)/venv"
    - rm -rf "$CI_VENV"
    - python -mvenv "$CI_VENV"
    - source "$CI_VENV/bin/activate"
    - python -mpip install --upgrade pip setuptools wheel
    - python -mpip install --upgrade pytest pytest-cov
    - python -mpip install .
  script:
    - echo "Trying to launch pytest..."
    - python -mpytest
    - echo "Trying to launch coverage"
    - coverage run -m pytest 
    - coverage report
    - coverage xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
