coverage-job:
  stage: test
  image: quay.io/pypa/manylinux2014_x86_64
  before_script:
    - PYTHON_ROOT=/opt/python/cp38-cp38
    - export PATH=$PYTHON_ROOT/bin:$PATH
    - echo "Loaded $(python -V)"
    - CI_VENV="$(pwd)/venv"
    - rm -rf "$CI_VENV"
    - python -mvenv "$CI_VENV"
    - source "$CI_VENV/bin/activate"
  script:
    - pip install pytest pytest-cov
    - coverage run -m pytest 
    - coverage report
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml

test-job:
  tags:
    - bb5_user
  variables:
    bb5_account: proj83
  stage: test
  before_script:
    - module load unstable python py-bluepy py-virtualenv
    - CI_VENV="$(pwd)/venv"
    - rm -rf "$CI_VENV"
    - python -mvenv "$CI_VENV"
    - source "$CI_VENV/bin/activate"
    - python -mpip install --upgrade pip setuptools wheel
    - python -mpip install --upgrade pytest
    - python -mpip install .
  script:
    - echo "Trying to launch pytest..."
    - python -mpytest

