build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job:
  tags:
    - bb5_user
  stage: test
  before_script:
    - module load unstable python py-bluepy py-virtualenv
    - CI_VENV="$(pwd)/venv"
    - rm -rf "$CI_VENV"
    - python -mvenv "$CI_VENV"
    - source "$CI_VENV/bin/activate"
    - python -mpip install --upgrade pip setuptools wheel
    - python -mpip install --upgrade pytest
    - python -mpip install .
  script:
    - echo "Trying to launch pytest..."
    - python -mpytest

